// import './globals.css'
"use client";
import baseTheme from "@/chakra-ui/theme";
import Navbar from "@/components/layout/Navbar";
import { ChakraProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "../public/css/slider.css";
import "../public/css/index.css";
import "../public/css/contact.css";
import Footer from "@/components/layout/Footer";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import Contact from "@/components/contact-fixed/Contact";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <Contact />
          <ChakraProvider theme={baseTheme}>
            <Navbar />
            {children}
            <Footer />
          </ChakraProvider>
        </Provider>
      </body>
    </html>
  );
}
